replicaCount: 2

image:
  repository: nkaplan19/adjust-test 
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "adjust-app"
fullnameOverride: "adjust-app"


securityContext: 
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  enabled: true
  name: adjust-service
  type: NodePort
  externalPort: 5000
  internalPort: 5000

ingress:
  enabled: true
  class: "nginx"
  rules:
    - host: test.adjust.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adjust-service
                port:
                  number: 5000

resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 85

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate
